name: noble-ab
version: '1.0.1'
base: core18
summary: nodejs application to access bluetooth
description: |
grade: devel
confinement: devmode
parts:
  node:
    plugin: nodejs
    nodejs-package-manager: npm
    source: https://github.com/ojousima/node-ruuvitag
    source-type: git
    build-packages: [python]
    stage-packages:
      - libbluetooth-dev 
      - libudev-dev
      
  
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
apps:
  npm:
    command: npm
    plugs:
      - home
      - network
      - network-bind
  node:
    command: node
    plugs:
      - home
      - network
      - network-bind
