name: tsbt
version: '1.3.3'
base: core18
summary: nodejs application to access bluetooth tsbt tags
description: |
      tsbt reader and usbutils
grade: devel
confinement: devmode

parts:
  local-scripts:
    plugin: dump
    source: .
    override-prime: |
      snapcraftctl prime
      chmod 770 enableBle.sh
      chown root enableBle.sh
  tsbt:
    plugin: nodejs
    build-packages: [npm, python]
    source: .
    stage-packages: 
      - libbluetooth-dev 
      - libudev-dev
      - build-essential
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm   
  espruino:
    plugin: dump
    source: https://github.com/espruino/EspruinoHub
    source-type: git
    organize:
      '*': EspruinoHub/

  espruino-tools:
    plugin: dump
    build-packages: [npm] 
    source: https://github.com/espruino/EspruinoTools.git 
    source-type: git  
    organize:
      '*': EspruinoTools/
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm   


  usbutils:
    plugin: autotools
    source: https://github.com/gregkh/usbutils.git
    source-type: git
    stage-packages:
      - libusb-1.0-0
    build-packages:
      - npm
      - libusb-1.0-0-dev
      - libglib2.0-dev
      - libudev-dev
      - zlib1g-dev
    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --localstatedir=/var/lib
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm
 
      
  
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
plugs:
  client:
      interface: bluez
apps:
  lsusb:
    command: usr/bin/lsusb
    plugs: [hardware-observe, network]

    
  tsbt:
    command-chain: 
      - ./enableBle.sh
    command: node $SNAP/index.js
    daemon: simple
    start-timeout: 30s
    plugs:
      - client
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
  node:
    command: node
    plugs:
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
  espr:
    command: node $SNAP/EspruinoTools/index.js
    plugs:
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
