name: tsbt
version: '1.3.0'
base: core18
summary: nodejs application to access bluetooth ruuvies
description: |
      ruuvi reader and usbutils
grade: devel
confinement: devmode

parts:
  top:
    plugin: nodejs
    build-packages: [npm, python]
    source: .
    stage-packages:
      - libbluetooth-dev 
      - libudev-dev
      - build-essential
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm   
      
  usbutils:
    plugin: autotools
    source: https://github.com/gregkh/usbutils.git
    source-type: git
    stage-packages:
      - libusb-1.0-0
    build-packages:
      - npm
      - libusb-1.0-0-dev
      - libglib2.0-dev
      - libudev-dev
      - zlib1g-dev
    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --localstatedir=/var/lib
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm
 
      
  
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
apps:
  lsusb:
    command: usr/bin/lsusb
    plugs: [hardware-observe, network]

    
  ruuvi:
    command: node $SNAP/index.js
    daemon: simple
    start-timeout: 10s
    plugs:
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
  node:
    command: node
    plugs:
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
