name: tsbt
version: '1.3.6'
base: core18
summary: nodejs application to access bluetooth tsbt tags
description: |
      tsbt reader and usbutils
grade: devel
confinement: devmode

parts:
   bluez:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp hciattach $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp init-bluetooth $SNAPCRAFT_PART_INSTALL/usr/bin/
  local-scripts:
    plugin: dump
    source: .
  tsbt:
    plugin: nodejs
    build-packages: [npm, python]
    source: .
    build-snaps:
      - bluez
      - ngrok
    stage-snaps:
      - bluez
      - ngrok
    stage-packages: 
      - libbluetooth-dev 
      - libudev-dev
      - build-essential
      - libreadline-dev
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm   

  espruino-tools:
    plugin: dump
    build-packages: [npm] 
    source: https://github.com/espruino/EspruinoTools.git 
    source-type: git  
    organize:
      '*': EspruinoTools/
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm   


  usbutils:
    plugin: autotools
    source: https://github.com/gregkh/usbutils.git
    source-type: git
    stage-packages:
      - libusb-1.0-0
    build-packages:
      - npm
      - libusb-1.0-0-dev
      - libglib2.0-dev
      - libudev-dev
      - zlib1g-dev
    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --localstatedir=/var/lib
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm
 
      
  
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
plugs:
  client:
      interface: bluez
apps:
  lsusb:
    command: usr/bin/lsusb
    plugs: [hardware-observe, network]

  ngrokHttp:
    command: ./ngrok http -subdomain kfv.cgo.tsbt 3000
    daemon: simple
    start-timeout: 10s
    plugs:
      - client
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control

  init:
    command: init-bluetooth
    daemon: simple
    plugs:
      - serial-port
  hciattach:
    command: usr/bin/hciattach
    plugs:
      - serial-port

  ngrokSSH:
    command: ./ngrok tcp --remote-addr=3.tcp.ngrok.io:23398 22
    daemon: simple
    start-timeout: 60s
    plugs:
      - client
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
  
  tsbt:
    command: node $SNAP/index.js
    daemon: simple
    start-timeout: 30s
    plugs:
      - client
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
  node:
    command: node
    plugs:
      - home
      - network
      - network-bind
      - bluetooth-control
      - network-control
  espr:
    command: node $SNAP/EspruinoTools/bin/espruino-cli.js
    plugs:
      - client
      - home
      - network
      - network-bind
      - bluetooth-control 
      - network-control
