name: noble-ab
version: '1.1.0'
base: core18
summary: nodejs application to access bluetooth
description: |
      ruuvi reader and usbutils
grade: devel
confinement: devmode

parts:

  usbutils:
    plugin: autotools
    source: https://github.com/gregkh/usbutils.git
    source-type: git
    stage-packages:
      - libusb-1.0-0
    build-packages:
      - npm
      - libusb-1.0-0-dev
      - libglib2.0-dev
      - libudev-dev
      - zlib1g-dev
    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --localstatedir=/var/lib
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/bin/npm
  ruuvi:
    plugin: nodejs
    nodejs-package-manager: npm
    source: https://github.com/ojousima/node-ruuvitag
    source-type: git
    build-packages: [python]
    stage-packages:
      - libbluetooth-dev 
      - libudev-dev
      - build-essential
      
  
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
apps:
  lsusb:
    command: usr/bin/lsusb
    plugs: [hardware-observe, network]
    aliases:
      - lsusb
  npm:
    command: npm
    plugs:
      - home
      - network
      - network-bind
  node:
    command: node
    plugs:
      - home
      - network
      - network-bind
  ruuvi:
    command: node /snap/noble-ab/current/ruuvi.js
    plugs:
      - home
      - network
      - network-bind
      - bluetooth-control
      - client
      - home
      - network-control
